version: "3.8"
services:
  php74:
    container_name: php74
    hostname: php74
    image: langdonglei/php74:latest
    network_mode: bridge
    restart: always
    volumes: 
      - ../../:/www
      - ../vhost:/etc/nginx/conf.d
    ports:
      - "80:80" 
      - "3333:3333"
      - "5555:5555"
      - "6379:6379"
