version: "3.8"
services:
  php:
    container_name: php
    hostname: dev
    image: langdonglei/dev:latest
    restart: always
    network_mode: bridge
    ports:
      - "80:80" 
      - "3333:3333"
    volumes: 
      - ../:/root/www
      - ./vhost:/etc/nginx/conf.d
    privileged: true
    entrypoint: /sbin/init
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306" 
