version: "3.8"
services:
  dev:
    container_name: dev
    hostname: dev
    image: langdonglei/dev:latest
    network_mode: bridge
    ports:
      - "80:80" 
      - "6379:6379"
      - "3333:3333"
    volumes: 
      - ../:/root/www
      - ./vhost:/etc/nginx/conf.d
    privileged: true
    entrypoint: /sbin/init

