version: "3.8"
services:
  dev:
    image: langdonglei/dev:latest
    restart: always
    network_mode: bridge
    hostname: dev
    container_name: dev
    volumes:
      - ./:/www
    ports:
      - "80:80"
      - "3333:3333"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "6379:6379"
