version: "3.8"
services:
  mysql:
    container_name: mysql80
    hostname: mysql80
    image: mysql:8.0
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
