version: "3.8"
services:
  php:
    container_name: php
    hostname: php
    image: langdonglei/php:latest
    network_mode: bridge
    restart: always
    volumes: 
      - ../../:/www
      - ../vhost:/etc/nginx/conf.d
    ports:
      - "80:80" 
      - "3333:3333"
      - "5555:5555"
      - "6379:6379"
    command: ["sh","-c","nginx && redis-server /etc/redis.conf"]
