on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: s1 -> Check Out Repo
        uses: actions/checkout@v2
      - name: s2 -> Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: s3 -> Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: s4 -> Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dev:latest
      - name: s5 -> Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
